const card = [
    { word : 'Cat', img : '/img/Cat.svg' },
    { word : 'Dog', img : '/img/Dog.svg' },
    { word : 'Frog', img : '/img/Frog.svg'},
    { word : 'Horse', img : '/img/Horse.svg' },
    { word : 'Wolf', img : '/img/Wolf.svg' },
    { word : 'Duck', img : '/img/Duck.svg' },
    { word : 'Fox', img : '/img/Fox.svg' },
    { word : 'Lion', img : '/img/Lion.svg' },
    { word : 'Fish', img : '/img/Fish.svg' },
    { word : 'Tiger', img : '/img/Tiger.svg' },
    { word : 'Pig', img : '/img/Pig.svg' },
    { word : 'Mouse', img : '/img/Mouse.svg' },
    { word : 'Ant', img : '/img/Ant.svg' },
    { word : 'Bear', img : '/img/Bear.svg' },
    { word : 'Rabbit', img : '/img/Rabbit.svg' },
    { word : 'Snake', img : '/img/Snake.svg' },
    { word : 'Apple', img : '/img/Apple.svg' },
    { word : 'Pear', img : '/img/Pear.svg' },
    { word : 'Bee', img : '/img/Bee.svg' },
    { word : 'Ice cream', img : '/img/IceCream.svg' },
    { word : 'Egg', img : '/img/Egg.svg' },
    { word : 'Cupcake', img : '/img/Cupcake.svg' },
    { word : 'Banana', img : '/img/Banana.svg' },
    { word : 'Ball', img : '/img/Ball.svg' },
    { word : 'Car', img : '/img/Car.svg' },
    { word : 'Ice', img : '/img/Ice.svg' },
    { word : 'Key', img : '/img/Key.svg' },
    { word : 'Mushroom', img : '/img/Mushroom.svg' },
    { word : 'Umbrella', img : '/img/Umbrella.svg' },
    { word : 'Train', img : '/img/Train.svg' },
    { word : 'Leg', img : '/img/Leg.svg' },
    { word : 'Hand', img : '/img/Hand.svg' }
];

export default card;